### ISSUE TITLE
Duplicate Settings Menu

### ISSUE THREAD

**Issue by mccallum-sgd** [SWW13/language-x86asm#12] opened 2018-03-01 21:32 UTC
Hi, for me when I go to the package settings there are two settings menus that I believe are exactly the same. Unless they do something different?

Not a huge issue but I assume one takes precedence over the other? I haven't changed many of the default settings but for someone who does it might be annoying to have to do everything twice.

**Comment by SWW13** [comment] 2018-03-02 21:07
I can't reproduce duplicate settings.
Where exactly do you see duplicate settings?

![language-x86asm
 settings](https://user-images.githubusercontent.com/1280142/36921745-ba6f423a-1e65-11e8-9203-5cad52d648c2.png)

**Comment by mccallum-sgd** [comment] 2018-03-02 22:51
Hmm.. well it was happening for me:
![issue_12record 2](https://user-images.githubusercontent.com/23219638/36925726-6f5ba7ae-1e31-11e8-8197-714a43c2824b.gif)
A quick uninstall and reinstall just fixed it though. Not sure what happened, that's weird.

**Comment by SWW13** [comment] 2018-03-03 10:47
Very strange, maybe an upstream atom bug.
I'm closing it here as invalid.

**Closed as completed** 2018-03-03 10:47 UTC
Labels: invalid
